name: five_page_navigation
description: "This package allows you to navigate between screen from one central page. You can swipe up, down, left and right with ease."
version: 1.0.5
homepage: https://github.com/metekaganmusaak/five_page_navigation
issue_tracker: https://github.com/metekaganmusaak/five_page_navigation/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

screenshots:
  - description: "Package Logo"
    path: assets/five_page_navigation.png
